config/routes.rb
MangaChecker::Application.routes.draw do

  root :to => "check_update#index"
  get "check_update/logout"
  get "check_update/index"
  get "check_update/show"
  get "check_update/add_url_form"
  get "check_update/check_updates"
  get "check_update/delete"
  get "check_update/delete_list"
  post "check_update/add_url"
  get "check_update/add_url"
  get "home/index"
  get "check_update/redirect"
  get "check_update/ranking"
  get "check_update/check_update"
  get "check_update/check_maximum_id"
  get "check_update/update_all_history"

  devise_for :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MangaChecker" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9] >
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">MangaChecker</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav pull-right">
	      <% if current_user %>
		<li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
	      <% else %>
	        <li><%= link_to "ユーザ登録", new_user_registration_path %></li>
	        <li><%= link_to "ログイン", new_user_session_path %></li>
	      <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>


    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li><%= link_to "ランキング" , check_update_ranking_path %></li>
	      <% if current_user %>
              <!-- <li class="nav-header">Sidebar</li> -->
              <li><%= link_to "チェックリスト" , :controller => "check_update", :action => "show" %></li>
              <li><%= link_to "URL追加" , :controller => "check_update" , :action => "add_url_form" %></li>
              <li><%= link_to "削除" , :controller => "check_update" , :action => "delete_list" %></li>
	      <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->


      <footer>
        <p>&copy; <a href="https://github.com/rasenn/check_hp_update" target="_blank">@RASENN</a> 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>